### ISSUE TITLE
work out an idea how the version control will work

### ISSUE THREAD

**Issue by concept-core** [concept-core/projectMeet#8]

**Comment by concept-core** [comment]
@anthonyjb Should I implement this or should I let it out ?

**Comment by anthonyjb** [comment]
I'd recommend this article http://nvie.com/posts/a-successful-git-branching-model/ - we model very close to this approach on client projects (though I tend to use few branches (just master, develop and my own local) on personal library projects.

**Comment by concept-core** [comment]
And how do you feel about version control in web applications ?

For example, if I would edit a page on the website.
Would I want to keep those the changes in a separate table or would I just overwrite them ?

**Comment by anthonyjb** [comment]
Typically I store a change log so I can review who change what and when but I don't store revisions unless I intend to implement a mechanism allowing people to revert the state of a record (and any of it's related records).

Do you have a use case in your project for storing revisions?

**Comment by concept-core** [comment]
- [ ] Adding a package that will check for differences on the project requirement and project description pages.
- [ ] Maybe keep track of global changes that admin's can see.
